[build]
  command = "npm run build"
  publish = "dist/public"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20"
  MY_AWS_REGION = "us-east-1"

[functions]
  # Increase function timeout to 25 minutes (1500 seconds) to handle large batches
  node_bundler = "esbuild"
  timeout = 1500

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 