[build]
  command = "npm run build"
  publish = "dist/public"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20"
  MY_AWS_REGION = "us-east-1"

[functions]
  # Specify esbuild as the bundler
  node_bundler = "esbuild"

# Configure the api function specifically
[functions.api]
  timeout = 1500 # 25 minutes in seconds

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 